database:
  host: "localhost"
  port: 5432
  dbname: "your_db"
  user: "your_user"
  password: "your_password"

vector_store:
  redis_host: "localhost"
  redis_port: 6379
  # Remove chroma_path and collection names
